# Generated by Django 4.0.2 on 2022-07-31 19:24

from django.db import migrations, models
import petstagram.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pets/', validators=[petstagram.main.validators.validate_image]),
        ),
    ]
