# Generated by Django 4.0.2 on 2022-02-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
