# Generated by Django 4.0.2 on 2022-08-01 07:08

from django.db import migrations, models
import petstagram.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_petphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(default=1, upload_to='pets/', validators=[petstagram.main.validators.validate_image]),
            preserve_default=False,
        ),
    ]
